$body = @{
  uppscNews = @(
    # 2 Jul 2026
    @{ date="2 Jul 2026"; category="Exam"; headline="UPTET-2026 Begins: 19.94 Lakh Candidates Appear Across 60 Districts"; detail="UPTET-2026 examinations begin July 2-4 across 955 centres in 60 districts. CM Yogi directed zero tolerance against irregularities. Special security deployment around all exam centres. Prohibitory orders under Section 163 BNSS imposed."; relevance="High"; source="News Analysis"; tags="UPTET,Exam,Education" }
    @{ date="2 Jul 2026"; category="UP Economy"; headline="UPPSC PCS 2026 Notification: 500 Vacancies Released for Deputy Collector, DSP, BDO"; detail="UPPSC released PCS 2026 notification with approximately 500 vacancies including Deputy Collector, DSP, Block Development Officer, ARTO, and Naib Tehsildar. Application window open 25 June to 27 July 2026. Prelims scheduled December 6, 2026. Age limit 21-40 years."; relevance="High"; source="News Analysis"; tags="UPPSC,PCS,Recruitment,Vacancies" }
    @{ date="2 Jul 2026"; category="UP Infrastructure"; headline="UP Expressway Industrial Authority Plans Corridors Along Purvanchal Expressway"; detail="UPEIDA announces industrial corridor development along Purvanchal Expressway to boost investment and employment in eastern UP. Focus on food processing, textiles, and manufacturing sectors. Expected to generate 2 lakh direct jobs."; relevance="Medium"; source="News Analysis"; tags="Industry,Infrastructure,Employment,Purvanchal" }
    # 1 Jul 2026
    @{ date="1 Jul 2026"; category="UP Schemes"; headline="BRICS Culture Working Group Second Meeting Held in Varanasi"; detail="India hosted the Second BRICS Culture Working Group Meeting in Varanasi under India's BRICS Chairship 2026. Representatives from Brazil, Russia, China, South Africa and new members discussed cultural cooperation, heritage preservation and people-to-people exchanges."; relevance="Medium"; source="News Analysis"; tags="BRICS,Varanasi,Culture,International" }
    @{ date="1 Jul 2026"; category="UP Economy"; headline="UP's One District One Product Scheme Gets Rs 1,200 Crore Boost in New Budget"; detail="Uttar Pradesh government allocates Rs 1,200 crore under ODOP scheme for FY 2026-27. Scheme covers 75 districts with unique traditional products. Lucknow chikankari, Agra leather, Varanasi silk, Moradabad brass and Aligarh locks among key beneficiaries. Over 25 lakh artisans covered."; relevance="Medium"; source="News Analysis"; tags="ODOP,Economy,Handicrafts,Budget" }
    # 30 Jun 2026
    @{ date="30 Jun 2026"; category="UP Polity"; headline="UP Launches Mission Shakti Phase 4: New Features for Women Safety"; detail="UP government launched Mission Shakti Phase 4 with enhanced features including 1090 helpline integration, CCTV surveillance expansion to 5,000 new locations, and dedicated women safety desks in all 75 districts. Over 45 lakh women have benefited since scheme's launch."; relevance="High"; source="News Analysis"; tags="Mission Shakti,Women,Safety,Polity" }
    @{ date="30 Jun 2026"; category="UP Infrastructure"; headline="Ganga Expressway: 73% Construction Complete, Set to Open by March 2027"; detail="Ganga Expressway connecting Meerut to Prayagraj shows 73% construction completion. The 594 km expressway passes through 12 districts. Expected to reduce travel time from 12 hours to 6 hours. Total project cost Rs 36,230 crore."; relevance="Medium"; source="News Analysis"; tags="Expressway,Infrastructure,Transport,Ganga" }
    # 29 Jun 2026
    @{ date="29 Jun 2026"; category="UP Economy"; headline="Surha Tal in Ballia Becomes India's 100th Ramsar Site: Key Facts for UPPSC"; detail="Jai Prakash Narayan Bird Sanctuary (Surha Tal) in Ballia district designated India's 100th Ramsar site and world's 2,595th. Natural perennial oxbow lake in Ganga river basin. Hosts 221 plant species, 66 fish species. India now holds highest number of Ramsar sites in Asia, third globally after UK (176) and Mexico (144)."; relevance="High"; source="News Analysis"; tags="Ramsar,Ballia,Environment,Wetland,UPPSC" }
    @{ date="29 Jun 2026"; category="Agriculture"; headline="UP Launches Zero Stubble Burning Mission for Kharif 2026 Season"; detail="UP government launches campaign to eliminate stubble burning in Kharif season 2026. Alternative crop residue management through bio-decomposers, happy seeders and paddy straw management units. Incentive of Rs 2,500 per acre for compliant farmers. 15 lakh hectares of paddy cultivation targeted."; relevance="Medium"; source="News Analysis"; tags="Agriculture,Environment,Stubble,Farmers,Kharif" }
    # 28 Jun 2026
    @{ date="28 Jun 2026"; category="UP Schemes"; headline="CM Abhyudaya Scheme Covers 1.5 Lakh Students for Free UPSC-UPPSC Coaching"; detail="CM Abhyudaya Scheme has enrolled 1.5 lakh students for free coaching for UPSC, UPPSC, NDA, JEE, NEET and other competitive exams across 18 mandal headquarters. Best-in-state faculty provides guidance. Online live classes available via CM Abhyudaya app."; relevance="High"; source="News Analysis"; tags="Abhyudaya,Education,Coaching,UPPSC" }
    @{ date="28 Jun 2026"; category="Health"; headline="UP Establishes 100 New Pradhan Mantri Jan Aushadhi Kendras in Rural Areas"; detail="Uttar Pradesh government establishes 100 new PMJAK stores in rural blocks across 50 districts providing generic medicines at up to 90% less than branded drug prices. Total number of Jan Aushadhi Kendras in UP reaches 3,400. Monthly savings of Rs 500-800 per family estimated."; relevance="Medium"; source="News Analysis"; tags="Health,Jan Aushadhi,Rural,Medicines" }
    # 26 Jun 2026
    @{ date="26 Jun 2026"; category="UP Economy"; headline="BRICS Energy Ministers Meeting Held in Gurugram Under India's BRICS Chairship 2026"; detail="11th BRICS Energy Ministers Meeting convened in Gurugram, Haryana on June 25. India as BRICS Chair 2026 hosted discussions on clean energy transition, energy security, green hydrogen cooperation and affordable energy access. Representatives from all BRICS nations attended."; relevance="Medium"; source="News Analysis"; tags="BRICS,Energy,Economy,International" }
    @{ date="26 Jun 2026"; category="UP Polity"; headline="UP's Left-Wing Extremism Affected Districts Shrink from 46 to Just 5 Under Yogi Govt"; detail="Districts affected by Left-Wing Extremism in UP have declined from 46 in 2017 to just 5 in 2026. Combined surrender, development and security approach implemented. Naxal-related incidents dropped by 87%. All 5 remaining affected districts in Sonbhadra and Mirzapur divisions."; relevance="Medium"; source="News Analysis"; tags="LWE,Naxal,Polity,Security,Development" }
    # 25 Jun 2026
    @{ date="25 Jun 2026"; category="UP Infrastructure"; headline="UP Tourism Launches Visit My State Campaign: 10 New Heritage Circuits Announced"; detail="Uttar Pradesh Tourism department launched Visit My State campaign with 10 new heritage and spiritual tourism circuits. Focus on Ramayana Circuit, Vrindavan, Chitrakoot, Vindhyachal and Dudhwa. 50 new eco-tourism sites to be developed. Rs 800 crore allocated for tourism infrastructure."; relevance="Medium"; source="News Analysis"; tags="Tourism,Heritage,Culture,Infrastructure" }
    # 22 Jun 2026
    @{ date="22 Jun 2026"; category="Law & Order"; headline="Lucknow Coaching Fire: 15 Dead, UP Govt Orders Fire Safety Audit of All Coaching Centres"; detail="At least 15 people killed in Lucknow coaching centre fire on June 22. UP government ordered mandatory fire safety audit of all coaching institutes within 30 days. Buildings without NOC from fire department to be sealed. New building code enforcement for educational institutions announced."; relevance="High"; source="News Analysis"; tags="Fire,Lucknow,Safety,Education,Law" }
    @{ date="22 Jun 2026"; category="Education"; headline="UP Board Results 2026: Overall Pass Percentage Rises to 82.3%, Girls Outperform Boys"; detail="UP Board High School and Intermediate results 2026 declared. Overall pass percentage rises to 82.3% from 79.8% last year. Girls' pass rate at 85.1% vs boys 80.2%. Prayagraj district tops performance. 56.7 lakh students appeared across both classes this year."; relevance="Medium"; source="News Analysis"; tags="Education,Board,UP Board,Results" }
    # 18 Jun 2026
    @{ date="18 Jun 2026"; category="Agriculture"; headline="World Desertification Day 2026: India Restores 30 Lakh Hectares Under WDC-PMKSY 2.0"; detail="World Day to Combat Desertification and Drought observed on June 17 with theme 'Rangelands: Recognize. Respect. Restore.' India restored 30 lakh hectares of degraded land under WDC-PMKSY 2.0. About 29.7% of India's total geographical area affected by land degradation."; relevance="Medium"; source="News Analysis"; tags="Environment,Desertification,PMKSY,Land" }
    @{ date="18 Jun 2026"; category="UP Economy"; headline="UP's ODOP Export Crosses Rs 2 Lakh Crore: Highest in India Among State Schemes"; detail="UP's One District One Product scheme achieves exports worth Rs 2 lakh crore making it the highest earning state scheme in India. Varanasi silk, Bhadohi carpets, Moradabad brass, Agra leather, Firozabad glass bangles among top earners. 44 lakh artisans and workers directly engaged."; relevance="Medium"; source="News Analysis"; tags="ODOP,Export,Economy,Handicrafts" }
    # 15 Jun 2026
    @{ date="15 Jun 2026"; category="UP Polity"; headline="IAS e-Civil List 2026 Released: 71st Edition Digitizes IAS Officer Data Across India"; detail="Ministry of Personnel released IAS e-Civil List 2026 (71st edition, 6th digital edition) containing comprehensive service details of all IAS officers. Enables online access to cadre-wise posting details, batch information and service records. Supports transparency in civil services administration."; relevance="Low"; source="News Analysis"; tags="IAS,Civil Services,Administration,Polity" }
    @{ date="15 Jun 2026"; category="UP Schemes"; headline="UP Smart Cities Mission: 17 Cities Complete Infrastructure Projects Worth Rs 8,000 Crore"; detail="Uttar Pradesh's 17 Smart Cities complete major infrastructure projects worth Rs 8,000 crore under Smart Cities Mission. Lucknow, Agra, Varanasi, Prayagraj among top performers. ICT-enabled governance, smart traffic management and integrated command-control centres operationalized."; relevance="Medium"; source="News Analysis"; tags="Smart Cities,Infrastructure,Urban,Development" }
    # 7 Jun 2026
    @{ date="7 Jun 2026"; category="UP Polity"; headline="UP Police Launches Project Hawk Eye for Amarnath Yatra 2026 Security"; detail="Uttar Pradesh and J&K Police launch Project Hawk Eye with drone surveillance, 500+ CCTV cameras, facial recognition systems, sniper teams and ground observation posts for Amarnath Yatra 2026. Real-time monitoring from integrated command centre in Anantnag. Pilgrimage began June 29."; relevance="Medium"; source="News Analysis"; tags="Amarnath,Security,Police,Technology" }
    @{ date="7 Jun 2026"; category="Agriculture"; headline="UP Kisan Sarthi App: 1 Crore Farmers Get Direct Advisory on Crops and Pesticides"; detail="UP government's Kisan Sarthi mobile app crosses 1 crore active users. App provides personalized crop advisory, weather alerts, market prices and pesticide recommendations based on GPS location and soil data. Integration with PM KISAN Samman Nidhi enables direct subsidy claims."; relevance="Medium"; source="News Analysis"; tags="Agriculture,Technology,Farmers,App,Kisan" }
    # 5 Jun 2026
    @{ date="5 Jun 2026"; category="Environment"; headline="World Environment Day 2026: UP Plants 35 Crore Saplings Under Tree Plantation Drive"; detail="On World Environment Day (June 5), UP government plants 35 crore saplings in single day, setting national record. Campaign covers 75 districts with participation from school students, NSS volunteers and government employees. UP's forest cover has increased by 127 sq km since 2019."; relevance="Medium"; source="News Analysis"; tags="Environment,Plantation,Climate,UP" }
  )
  currentAffairs = @(
    # 2 Jul 2026
    @{ date="2 Jul 2026"; category="International"; headline="16th India-Japan Annual Summit: PM Modi, PM Takaichi Sign 5 Key Agreements"; detail="Japanese PM Sanae Takaichi visited India July 1-3 for 16th Annual Summit. Both sides signed agreements on semiconductor supply chains, clean energy, defence equipment co-production, digital public infrastructure, and the Hiroshima-Nagasaki Peace Memorial collaboration. Japan to invest Rs 5 lakh crore in India by 2030."; relevance="High"; source="News Analysis"; tags="Japan,Summit,International,Trade,Defence" }
    @{ date="2 Jul 2026"; category="Science & Tech"; headline="Index of Services Production (ISP) Launched: Monthly Output Measure for Services Sector"; detail="Government launches Index of Services Production to measure monthly changes in real output of services sector - a direct counterpart to IIP for industrial sector. Base year 2022-23. Covers IT, banking, retail, transport, hospitality subsectors. Will improve economic data granularity for policy-making."; relevance="High"; source="News Analysis"; tags="Economy,Services,Statistics,ISP,IIP" }
    # 1 Jul 2026
    @{ date="1 Jul 2026"; category="Economy"; headline="RBI MPC Keeps Repo Rate at 5.25%, GDP Forecast Cut to 6.6% for FY27"; detail="RBI's Monetary Policy Committee unanimously maintained repo rate at 5.25% with neutral stance in June 2026 meeting. FY27 GDP forecast revised down to 6.6% from 6.9% due to West Asia tensions and global supply disruptions. CPI inflation forecast raised to 5.1% from 4.6%. Standing Deposit Facility rate stays at 5%."; relevance="High"; source="News Analysis"; tags="RBI,MPC,Repo Rate,Inflation,GDP,Economy" }
    @{ date="1 Jul 2026"; category="Polity"; headline="FCRA 2.0 Portal and e-OCI Card Launched by Home Minister Amit Shah"; detail="Union Home Minister Amit Shah launched FCRA 2.0 Portal for streamlined foreign contribution regulation and e-Overseas Citizen of India Card on June 30. e-OCI is a digitally verifiable card replacing physical OCI card. FCRA 2.0 reduces compliance burden for NGOs and educational institutions receiving foreign funds."; relevance="High"; source="News Analysis"; tags="FCRA,OCI,Home Ministry,Digital,Governance" }
    # 30 Jun 2026
    @{ date="30 Jun 2026"; category="Economy"; headline="India GDP Grew 7.7% in FY 2025-26: Now 3rd Largest Economy by PPP Surpassing Japan"; detail="India's GDP grew 7.7% in FY2025-26. IMF data confirms India surpassed Japan to become world's 3rd largest economy by Purchasing Power Parity at $14.6 trillion. Manufacturing grew 8.9%, services 7.2%, agriculture 4.1%. India targets becoming $5 trillion economy in nominal terms by 2027."; relevance="High"; source="News Analysis"; tags="GDP,Economy,PPP,Growth,IMF" }
    @{ date="30 Jun 2026"; category="Environment"; headline="India's Updated NDC: 50% Renewable Energy by 2030, Net Zero by 2070 Submitted to UNFCCC"; detail="India submitted updated Nationally Determined Contributions to UNFCCC committing to 50% non-fossil electricity capacity by 2030 (up from 40%), net zero by 2070. Green hydrogen target of 5 MMT/year by 2030 included. Climate finance demand of $1 trillion from developed nations stated."; relevance="High"; source="News Analysis"; tags="Climate,Environment,NDC,Renewable,UNFCCC" }
    # 29 Jun 2026
    @{ date="29 Jun 2026"; category="International"; headline="India-Seychelles Partnership: PM Modi Launches Ocean of Opportunity Initiative"; detail="PM Modi's state visit to Seychelles (June 27-29) results in Ocean of Opportunity maritime initiative. MoUs signed on maritime security, blue economy, digital connectivity, climate resilience and defense. India to provide $100 million credit line for coastal surveillance systems and 2 patrol vessels."; relevance="High"; source="News Analysis"; tags="Seychelles,International,Ocean,Maritime,Modi" }
    @{ date="29 Jun 2026"; category="Polity"; headline="Delhi Electric Vehicle Policy 2026 Approved: 50% New Vehicles to be EV by 2030"; detail="Delhi Cabinet approved EV Policy 2026 targeting 50% new vehicle registrations as electric by 2030. Rs 7,500 subsidy per kWh for two-wheelers, Rs 30,000 flat subsidy for e-autos. 1,000 new EV charging stations to be set up. Old diesel vehicles over 10 years to be scrapped compulsorily."; relevance="High"; source="News Analysis"; tags="EV,Delhi,Environment,Transport,Policy" }
    @{ date="29 Jun 2026"; category="Science & Tech"; headline="DRDO Hands Over Netra AEW&C Final Operational Clearance to Indian Air Force"; detail="DRDO handed over Final Operational Clearance certificate of indigenous Netra Airborne Early Warning and Control System to IAF. Developed by Centre for Airborne Systems (CABS). System provides 360-degree radar coverage, can track multiple aerial targets simultaneously and direct fighter aircraft. Enhances India's surveillance sovereignty."; relevance="High"; source="News Analysis"; tags="DRDO,IAF,Defence,Netra,AWACS" }
    # 28 Jun 2026
    @{ date="28 Jun 2026"; category="Sports"; headline="India Wins Bronze at AVC Men's Volleyball Cup 2026 Held in Ahmedabad"; detail="India won bronze medal at AVC (Asian Volleyball Confederation) Men's Volleyball Cup 2026 held in Ahmedabad, Gujarat from June 20-28. India defeated Kazakhstan 3-1 in bronze medal match. This is India's best finish in the tournament in 12 years. Tournament hosted across Ahmedabad's newly constructed multi-sport complex."; relevance="Medium"; source="News Analysis"; tags="Sports,Volleyball,AVC,Ahmedabad,Bronze" }
    @{ date="28 Jun 2026"; category="International"; headline="Operation Amistad: India Sends Humanitarian Aid to Venezuela After Earthquakes"; detail="India launched Operation Amistad on June 26 to provide humanitarian assistance to Venezuela after two earthquakes caused deaths and injuries. NDRF teams deployed along with relief materials including medicines, food, tents and water purification equipment. India-Venezuela bilateral relations strengthen through humanitarian diplomacy."; relevance="Medium"; source="News Analysis"; tags="Venezuela,Humanitarian,Earthquake,International,Operation" }
    # 26 Jun 2026
    @{ date="26 Jun 2026"; category="International"; headline="Iran-India Civilizational Ties: PM Modi Invited to Khamenei Funeral in Tehran"; detail="Following death of Iranian Supreme Leader Ayatollah Khamenei in US-Israel strikes (February 2026), Iran extended invitation to PM Modi for state funeral. India-Iran ties cover Chabahar Port, energy imports, cultural heritage (Mughal-Persian connections) and Afghan peace. India balancing relations amid US sanctions on Iran."; relevance="High"; source="News Analysis"; tags="Iran,International,Diplomacy,India,West Asia" }
    @{ date="26 Jun 2026"; category="International"; headline="India-South Korea Shipbuilding Deal: Korean President Lee Jae Myung's Historic Visit"; detail="South Korean President Lee Jae Myung made historic visit to India - first by a Korean leader in 8 years. Major shipbuilding partnership announced with Hyundai Heavy Industries and Daewoo Shipbuilding. India targets becoming top-5 global shipbuilding nation by 2040. India's current shipbuilding share is just 1% of global market."; relevance="High"; source="News Analysis"; tags="South Korea,Shipbuilding,International,Economy,Defence" }
    @{ date="26 Jun 2026"; category="Polity"; headline="31% of Rajya Sabha MPs Have Criminal Cases: ADR-National Election Watch Report"; detail="ADR and National Election Watch report reveals 31% of sitting Rajya Sabha MPs have declared criminal cases in affidavits, with 16% facing serious charges including murder, rape, kidnapping. Report highlights need for stronger electoral reforms. Supreme Court's VVPAT guidelines also under review by Election Commission."; relevance="High"; source="News Analysis"; tags="Rajya Sabha,Parliament,Crime,ADR,Polity,Electoral Reform" }
    @{ date="26 Jun 2026"; category="Science & Tech"; headline="AIR SUVIDHA 2.0 Portal Launched for Health Screening of International Passengers at Airports"; detail="Ministry of Civil Aviation and DIAL launched AIR SUVIDHA 2.0, upgraded online health screening portal for international arrivals. Launched amid Ebola concerns in West Africa. Portal mandates pre-arrival health declarations, enables QR code verification, reduces manual screening time from 45 minutes to 8 minutes. Operational at all 7 international airports."; relevance="Medium"; source="News Analysis"; tags="Aviation,Health,Digital,Airport,Screening" }
    # 25 Jun 2026
    @{ date="25 Jun 2026"; category="Polity"; headline="India Proposes BRICS Space Economy Collaborative Framework at Energy Ministers Meeting"; detail="Under India's BRICS Chairship 2026, India proposed BRICS Space Economy collaborative framework for joint satellite missions, shared launch infrastructure, and commercial space applications. Framework aims to reduce dependence on US and European space assets. India's ISRO to lead technical working group."; relevance="Medium"; source="News Analysis"; tags="BRICS,Space,ISRO,International,Technology" }
    @{ date="25 Jun 2026"; category="Economy"; headline="India's Total Fertility Rate Falls to 1.9: Below Replacement Level for First Time"; detail="India's Total Fertility Rate has fallen to 1.9, below the replacement level of 2.1, for first time. Southern states like Kerala (1.5), Tamil Nadu (1.7) and Andhra Pradesh (1.7) lead the decline. Bihar (2.9) and UP (2.4) remain above replacement. Demographic transition signals future ageing challenges for social security and healthcare."; relevance="High"; source="News Analysis"; tags="Demography,Population,TFR,Health,Economy" }
    # 23 Jun 2026
    @{ date="23 Jun 2026"; category="International"; headline="Hamburg Sustainability Conference 2026: India Commits to Green Finance Roadmap"; detail="India participated in Hamburg Sustainability Conference 2026, committing to Green Finance Roadmap including sovereign green bonds of Rs 25,000 crore, transition finance for coal-dependent districts, and biodiversity credits linked to forest conservation. India also signed Partnership for Green Growth with 12 European nations."; relevance="Medium"; source="News Analysis"; tags="Environment,Climate,Finance,International,Green" }
    @{ date="23 Jun 2026"; category="Polity"; headline="Naxal-Free India: LWE Districts Decline from 126 in 2014 to Just 2 by 2026"; detail="Union Home Ministry reports Left-Wing Extremism affected districts declined from 126 in 2014 to just 2 by 2026. Naxal-related violent incidents dropped from 870 in 2014 to 234 in 2025. Over 3,927 active cadres surrendered between 2024 and March 2026. Development-led security approach credited for success."; relevance="High"; source="News Analysis"; tags="Naxal,LWE,Security,Polity,Home Ministry" }
    # 22 Jun 2026
    @{ date="22 Jun 2026"; category="Disaster"; headline="15 Killed in Delhi Hotel Fire and Lucknow Coaching Centre Fire This Month"; detail="Dual fire tragedies claimed 15 lives at a coaching centre in Lucknow (June 22) and 21 at a Delhi hotel (June 3). Supreme Court suo motu took cognizance and directed states to submit fire safety compliance reports within 4 weeks. Centre issued revised National Building Code guidelines for commercial establishments."; relevance="High"; source="News Analysis"; tags="Fire,Disaster,Safety,Policy,Supreme Court" }
    # 20 Jun 2026
    @{ date="20 Jun 2026"; category="Environment"; headline="Kanchan Devi Committee Submits Aravalli Conservation Recommendations to Supreme Court"; detail="Supreme Court-appointed Kanchan Devi Committee submitted recommendations for Aravalli Range protection and classification. Recommendations include demarcating forest areas in Haryana and Rajasthan, restoring 1.2 lakh hectares of degraded Aravalli land and banning mining within 10 km of designated forest zones. Aravalli spans 691 km protecting Delhi from desertification."; relevance="High"; source="News Analysis"; tags="Environment,Aravalli,Supreme Court,Forest,Conservation" }
    @{ date="20 Jun 2026"; category="Economy"; headline="India's IIP Grows at 5-Month High of 5.1% in April 2026"; detail="India's Index of Industrial Production grew 5.1% in April 2026 - a five-month high. Manufacturing output expanded 5.6%, electricity generation rose 4.8%, mining grew 3.2%. Capital goods output surged 11.2% signalling investment recovery. Consumer durables grew 7.8% indicating urban demand revival."; relevance="High"; source="News Analysis"; tags="IIP,Industry,Economy,Manufacturing,Growth" }
    # 18 Jun 2026
    @{ date="18 Jun 2026"; category="Economy"; headline="Tamil Nadu Farm Loan Waiver of Rs 75,000 Despite Rs 13.18 Lakh Crore State Debt"; detail="Tamil Nadu government announced full waiver of cooperative crop loans up to Rs 75,000 even as state White Paper revealed Rs 13.18 lakh crore debt burden. RBI Internal Working Group (2019) had noted high correlation between loan waivers and election cycles. Economists warn of moral hazard, fiscal deterioration and crowding out of capital expenditure."; relevance="High"; source="News Analysis"; tags="Farm Loan,Economy,Fiscal,State Finance,Agriculture" }
    @{ date="18 Jun 2026"; category="Science & Tech"; headline="Indian Teenagers Win Earth Prize 2026 for Plas-Stick: Tamarind-Based Microplastic Remover"; detail="Three Indian teenagers won The Earth Prize 2026 for Plas-Stick, a biodegradable magnetic powder made from discarded tamarind seeds that removes microplastics from water. First Indian winners in Earth Prize history. When added to water, powder binds microplastic particles into clumps removable by handheld magnet. Earth Foundation established in Geneva in 2020."; relevance="Medium"; source="News Analysis"; tags="Innovation,Environment,Microplastics,Youth,Award" }
    # 15 Jun 2026
    @{ date="15 Jun 2026"; category="Economy"; headline="India-US Trade Target: $100 Billion Bilateral Trade Set for 2030 During PM Modi Visit"; detail="India and US set $100 billion bilateral trade target by 2030 during PM Modi's visit. Key sectors: defence ($10B), semiconductors, clean energy, pharmaceuticals. US Chips Act provisions extended to Indian manufacturers. India-US Initiative on Critical and Emerging Technology (iCET) expanded to include AI, quantum computing."; relevance="High"; source="News Analysis"; tags="USA,Trade,International,Technology,Economy" }
    # 10 Jun 2026
    @{ date="10 Jun 2026"; category="Polity"; headline="Ministry of Law Launches Notary Portal Fresh Application Module for Digital Notary Appointments"; detail="Ministry of Law and Justice launched Fresh Application Module on Notary Portal enabling eligible advocates to apply online for notary appointments. Covers 28 states and 8 UTs. Previously manual process taking 6-12 months now digitized to 45 days. Ministry also launched Legal Services Management System for District Legal Services Authorities."; relevance="Medium"; source="News Analysis"; tags="Law,Digital,Notary,Governance,Ministry" }
    @{ date="10 Jun 2026"; category="Economy"; headline="Cambodia Becomes 9th Country to Accept UPI: 4.5 Million Merchant Outlets Covered"; detail="Cambodia becomes 9th country where Indian travellers can pay via UPI, through partnership between NPCI International and ACLEDA Bank Plc. Over 4.5 million merchant outlets covered. Other 8 countries: Singapore, UAE, France, Mauritius, Nepal, Bhutan, Qatar, Sri Lanka. Second phase will enable two-way payment corridor."; relevance="High"; source="News Analysis"; tags="UPI,Digital Payment,International,NPCI,Cambodia" }
    # 7 Jun 2026
    @{ date="7 Jun 2026"; category="Economy"; headline="RBI Takes Measures to Stabilize Rupee as West Asia Conflict Raises Crude Prices"; detail="RBI undertook multiple measures in June 2026 to stabilize the Indian Rupee amid rupee depreciation pressure from rising crude oil prices due to West Asia conflict. Measures include forex intervention, relaxation of NRI deposit interest rate caps, and special dollar swap windows for importers. Rupee touched 85.4 per dollar."; relevance="High"; source="News Analysis"; tags="RBI,Rupee,Currency,Oil,Economy,West Asia" }
    @{ date="7 Jun 2026"; category="Environment"; headline="India's Monsoon 2026: 75% of Country Faces Deficient Rainfall Due to El Nino"; detail="IMD reports nearly 75% of India experiencing deficient rainfall in June 2026 due to El Nino conditions and unfavorable low-pressure systems. Northwest India 40% below normal. Kharif sowing delayed by 2-3 weeks. Government activates drought contingency plans in 8 states. NDMA advisory issued for water conservation."; relevance="High"; source="News Analysis"; tags="Monsoon,Climate,Agriculture,El Nino,Drought,IMD" }
    # 5 Jun 2026
    @{ date="5 Jun 2026"; category="Science & Tech"; headline="ISRO Achieves 7 Key Milestones in FY 2025-26: Gaganyaan Module Tests, Satellite Launches"; detail="ISRO achieved 7 milestones in FY 2025-26 including successful Gaganyaan crew module atmospheric re-entry test, launch of GSAT-24B communication satellite, NavIC constellation upgrade, Chandrayaan-4 mission design finalization, and PSLV's 65th successful launch. ISRO also signed space technology agreements with 12 countries."; relevance="High"; source="News Analysis"; tags="ISRO,Space,Gaganyaan,NavIC,Chandrayaan,Science" }
    @{ date="5 Jun 2026"; category="International"; headline="Norway Confers Highest Civilian Honour on PM Narendra Modi for Climate Leadership"; detail="Norway conferred its highest civilian honour on PM Narendra Modi recognizing India's leadership in renewable energy expansion and climate action. India's 2030 renewable energy target of 500 GW is one of the world's most ambitious. India's solar capacity crossed 200 GW in April 2026, second only to China."; relevance="Medium"; source="News Analysis"; tags="International,Norway,Environment,Modi,Solar,Climate" }
    # 3 Jun 2026
    @{ date="3 Jun 2026"; category="Disaster"; headline="21 Killed in Delhi Hotel Fire: Centre Orders Mandatory Fire Safety Audit of All Hotels"; detail="Fire at a hotel in Karol Bagh, New Delhi killed 21 on June 3. Union Ministry of Home Affairs ordered mandatory fire safety audit of all hotels with 50+ rooms within 60 days. Hotels without valid fire NOC to be sealed. States instructed to create district-level fire safety task forces with monthly reporting."; relevance="High"; source="News Analysis"; tags="Fire,Delhi,Safety,Hotel,Policy,Disaster" }
    @{ date="3 Jun 2026"; category="Economy"; headline="India's Shipbuilding Sector: Government Announces Rs 25,000 Crore Incentive Package"; detail="Government announces Rs 25,000 crore shipbuilding promotion scheme as India targets 5% global shipbuilding market share by 2040. Production-linked incentives for ship components manufacturing, reduced GST on shipbuilding inputs, and creation of Shipbuilding Clusters in Gujarat, Andhra Pradesh and Maharashtra announced."; relevance="High"; source="News Analysis"; tags="Shipbuilding,Economy,Manufacturing,Industry,Incentive" }
  )
} | ConvertTo-Json -Depth 5

$response = Invoke-RestMethod `
  -Uri "https://uppsc-pyq-production.up.railway.app/api/ingestNews" `
  -Method POST `
  -ContentType "application/json" `
  -Body $body

Write-Host "Response:" ($response | ConvertTo-Json)
