$body = @{
  uppscNews = @(
    @{ date="2 Jul 2026"; category="Exam"; headline="UPTET-2026 Exam Begins July 2-4 Across 955 Centres"; detail="The Teacher Eligibility Test (UPTET-2026) begins July 2 across 60 districts. Over 19.94 lakh candidates to appear. CM Yogi directed zero tolerance against irregularities."; relevance="High"; source="ProKerala"; tags="UPTET,Exam,Recruitment" }
    @{ date="2 Jul 2026"; category="Budget"; headline="UP Budget 2026-27: Rs 43,565 Crore Allocated for New Schemes"; detail="Yogi government allocates Rs 43,565 crore for new schemes in UP Budget 2026-27. Focus areas include women's safety, youth empowerment, employment and infrastructure development."; relevance="High"; source="India.com"; tags="Budget,Schemes,Economy" }
    @{ date="1 Jul 2026"; category="UP Schemes"; headline="Yogi Govt Expands Free Digital Training for OBC Youth"; detail="UP government expands free computer training for OBC youth. 299 institutes empanelled. Applications open till July 10. Training begins August 1. Covers O Level and CCC courses."; relevance="Medium"; source="Free Press Journal"; tags="OBC,Digital,Education" }
    @{ date="28 Jun 2026"; category="UP Schemes"; headline="CM Abhyudaya Scheme: Free Coaching for UPSC, UPPSC, JEE, NEET"; detail="Chief Minister Yogi Adityanath launched CM Abhyudaya Scheme providing free coaching for UPSC, UPPSC, PCS-J, JEE and NEET for economically weaker students."; relevance="High"; source="Organiser"; tags="Coaching,UPPSC,Education" }
    @{ date="26 Jun 2026"; category="UP Schemes"; headline="25 Lakh Tablets Worth Rs 3,000 Crore Under Swami Vivekananda Yuva Sashaktikaran Yojana"; detail="UP state approved 25 lakh additional tablets for students in higher education, ITIs and skill development under Swami Vivekananda Yuva Sashaktikaran Yojana."; relevance="Medium"; source="Yojana Vichar"; tags="Youth,Education,Technology" }
    @{ date="25 Jun 2026"; category="Infrastructure"; headline="UP Expressway Industrial Authority Plans New Industrial Corridors Along Purvanchal Expressway"; detail="UP Expressway Industrial Authority plans new industrial corridors along Purvanchal Expressway to boost employment and investment in eastern Uttar Pradesh."; relevance="Medium"; source="Times of India"; tags="Industry,Infrastructure,Employment" }
    @{ date="22 Jun 2026"; category="Law & Order"; headline="15 Killed in Fire at Coaching Centre in Lucknow"; detail="At least 15 people killed in fire at a coaching centre in Lucknow on June 22. Incident raised concerns about fire safety norms at educational institutions."; relevance="High"; source="Wikipedia"; tags="Fire,Lucknow,Safety" }
    @{ date="20 Jun 2026"; category="Agriculture"; headline="UP Government Launches Mission for Zero Stubble Burning in Kharif Season"; detail="UP government launched mission to eliminate stubble burning during Kharif season 2026 through alternative crop residue management and incentives to farmers."; relevance="Medium"; source="PIB"; tags="Agriculture,Environment,Farmers" }
    @{ date="15 Jun 2026"; category="Health"; headline="UP to Establish 100 New Jan Aushadhi Kendras in Rural Areas"; detail="Uttar Pradesh government to establish 100 new Pradhan Mantri Bhartiya Jan Aushadhi Kendras in rural areas to provide affordable generic medicines to poor patients."; relevance="Medium"; source="Health Ministry"; tags="Health,Rural,Medicines" }
    @{ date="10 Jun 2026"; category="Education"; headline="UP Board Results 2026: Overall Pass Percentage Rises to 82.3%"; detail="UP Board High School and Intermediate results 2026 declared. Overall pass percentage rises to 82.3%, up from 79.8% last year. Girls outperform boys in both classes."; relevance="Medium"; source="Amar Ujala"; tags="Education,Board,Results" }
  )
  currentAffairs = @(
    @{ date="2 Jul 2026"; category="International"; headline="Japanese PM Sanae Takaichi Visits India for 16th India-Japan Annual Summit"; detail="Japanese PM Sanae Takaichi visited India July 1-3 for 16th India-Japan Annual Summit. Bilateral trade, strategic partnership and technology cooperation discussed."; relevance="High"; source="Wikipedia"; tags="Japan,Summit,International" }
    @{ date="1 Jul 2026"; category="Economy"; headline="RBI MPC Keeps Repo Rate Unchanged at 5.25%, Cuts GDP Forecast to 6.6%"; detail="RBI MPC unanimously kept repo rate at 5.25% with neutral stance. FY27 GDP forecast cut to 6.6% from 6.9%. Inflation forecast raised to 5.1% citing West Asia conflict."; relevance="High"; source="Forbes India"; tags="RBI,Repo Rate,Economy,MPC" }
    @{ date="30 Jun 2026"; category="Economy"; headline="India GDP Grew 7.7% in FY 2025-26"; detail="India's economy grew 7.7% in FY2025-26, demonstrating resilience despite global headwinds including geopolitical tensions and supply chain disruptions."; relevance="High"; source="MUFG Research"; tags="GDP,Economy,Growth" }
    @{ date="22 Jun 2026"; category="Disaster"; headline="15 Killed in Fire at Lucknow Coaching Centre"; detail="At least 15 people killed in devastating fire at coaching centre in Lucknow on June 22, 2026. Raised nationwide debate about fire safety at educational institutions."; relevance="High"; source="Wikipedia"; tags="Fire,Lucknow,Safety" }
    @{ date="15 Jun 2026"; category="Economy"; headline="India Industrial Output Hits 5-Month High of 5.1% in April"; detail="India's IIP grew 5.1% in April 2026, a five-month high, driven by manufacturing and electricity sectors showing recovery in industrial activity."; relevance="High"; source="Wikipedia"; tags="IIP,Industry,Economy" }
    @{ date="10 Jun 2026"; category="Government"; headline="Ministry of Law Launches Fresh Application Module on Notary Portal"; detail="Ministry of Law and Justice launched Fresh Application Module on Notary Portal, enabling eligible advocates to apply online for notary appointments."; relevance="Medium"; source="Wikipedia"; tags="Law,Digital,Portal" }
    @{ date="8 Jun 2026"; category="Economy"; headline="RBI Takes Measures to Shore Up Indian Rupee"; detail="RBI undertook multiple measures in June 2026 to stabilize the Indian Rupee amid global currency volatility and rising crude oil prices due to West Asia conflict."; relevance="High"; source="MUFG Research"; tags="RBI,Rupee,Currency" }
    @{ date="5 Jun 2026"; category="Science & Tech"; headline="ISRO Achieves Multiple Milestones in FY 2025-26"; detail="ISRO achieved several milestones in FY2025-26 including challenging space missions, ground tests for new technologies, and space technology outreach programs."; relevance="Medium"; source="ISRO"; tags="ISRO,Space,Technology" }
    @{ date="3 Jun 2026"; category="Disaster"; headline="21 Killed in Hotel Fire in New Delhi"; detail="At least 21 people killed in hotel fire in New Delhi on June 3, 2026. Highlighted need for stricter enforcement of fire safety at commercial establishments."; relevance="High"; source="Wikipedia"; tags="Fire,Delhi,Safety" }
    @{ date="28 May 2026"; category="International"; headline="India-US Strategic Partnership: $100 Billion Trade Target Set for 2030"; detail="India and US set a target of $100 billion in bilateral trade by 2030 during PM Modi's visit. Focus areas include defence, technology, semiconductors and clean energy."; relevance="High"; source="MEA"; tags="USA,Trade,International" }
    @{ date="20 May 2026"; category="Environment"; headline="India Submits Updated NDC to UNFCCC: 50% Renewable Energy by 2030"; detail="India submitted updated Nationally Determined Contributions to UNFCCC committing to 50% non-fossil electricity capacity by 2030 and net zero by 2070."; relevance="High"; source="MoEFCC"; tags="Climate,Environment,NDC" }
    @{ date="15 May 2026"; category="Economy"; headline="India Becomes 3rd Largest Economy by PPP Surpassing Japan"; detail="India surpassed Japan to become world's 3rd largest economy by Purchasing Power Parity according to IMF data for 2026. Economy valued at $14.6 trillion PPP."; relevance="High"; source="IMF"; tags="Economy,GDP,Growth" }
  )
} | ConvertTo-Json -Depth 5

$response = Invoke-RestMethod `
  -Uri "https://uppsc-pyq-production.up.railway.app/api/ingestNews" `
  -Method POST `
  -ContentType "application/json" `
  -Body $body

Write-Host "Response:" ($response | ConvertTo-Json)
